# Generated by Django 2.2 on 2021-02-24 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0007_auto_20210220_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='subject_description',
            field=models.CharField(default=1, max_length=255),
        ),
    ]
