# Generated by Django 2.2 on 2021-02-25 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0010_auto_20210225_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects',
            name='budjet',
        ),
    ]
